### ISSUE TITLE
该作品还需要做一定的优化才可以使用

### ISSUE THREAD

**Issue by YinDongWu** [ChavezChen/CWDB#1]
希望作者可以再次更新。 无论是读写效率、线程安全、对外简单化都还有一定空间。  😏

**Comment by ChavezChen** [comment]
读写效率的问题可能我在插入时承载的业务有点多，稍微会影响，但是其实也是简于使用消耗了一点点性能，我测过一次插入2000条数据 时间在2.5秒左右，其实还能接受，线程安全我启动3子条线程，每条线程插入1000条数据，然后再启动3条子线程删除其中2900条数据，多次测试线程安全是没问题的。。对外简单化的话，可能我那里每个方法多两个参数是一点问题，但是这部分我在readme有做解释，也是为了迎合某一部分场景，我觉得这两个都是必要的。。提升空间肯定还有，我再看看，如果你有什么针对性的优化，可以提交一下，感谢建议。。😁
