### ISSUE TITLE
感谢哥们的Sqlite封装

### ISSUE THREAD

**Issue by wushengdubai** [ChavezChen/CWDB#3]
看到哥们的工具库，和我的这么像，亲切之前油然而生！看来咱们是看一个视频学习的啊~_~
还有，要十分感谢你把工具类完善的这么好，也帮到我解决了存储图片时，对Data数据转换的问题！

**Comment by ChavezChen** [comment]
哈哈，是的，但是那个讲的比较浅显，有一些问题，比如事务做的其实是不对的，那样操作事务没法成功，健壮性也挺差的，随便就崩溃了。主要还是从那学习思路，师傅领进门修行看个人啦，且我觉得入门是比较重要的一个步骤了。然后在做的时候查点资料补充一下细节就挺好了。。复杂的其实是模型、数组、字典嵌套的部分，比较绕，其他都好理解。一起加油吧。
